### ISSUE TITLE
Envoy stream_idle_timeout is resetting stream after 15minutes

### ISSUE THREAD

**Issue by pesc** [jalapeno-api-gateway/jagw#54]
Hi

You introduced (#46) the `stream_idle_timeout` in the Envoy config and set it to 900s = 15 minutes. Therefore we see every 15 minutes a reset while receiving the grpc stream if the network is stable and no data is received. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/2048399/203632216-d4b245f3-7140-44d1-ba1b-b700b0f283d3.png)

What is the reason for the `stream_idle_timeout`? Any idea how we can overcome those 15 minutes? Sending Keepalive does not help in this situation (https://github.com/grpc/grpc-go/blob/master/Documentation/keepalive.md)

Greetings Pascal

**Comment by ILLIDOM** [comment]
Hi Pascal,

It's nice to hear that you are using JAGW!

The ``stream_idle_timeout`` default value is 300s so if you don't set it inside the Envoy config the stream will be reset every 5 minutes. We had that problem in the past so I set the value inside the configuration file explicitly to make it clear why the stream is beeing reset.
Did you try setting the value of ``stream_idle_timeout`` to 0? This would completly disable the stream timeout. (see the explanation [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto).

**Comment by pesc** [comment]
Hi @ILLIDOM 

I see your point about setting an explicit value to clarify this problem. But I still don't get the point of resetting a **stream** every 15 minutes. If you consider your network stable and only subscribe to a few endpoints (LsNodes) then you will hit this default timeout quite often. 

For sure we could handle those 15-minute streams reset in our client. But as soon as the stream is terminating, we can not be sure not to miss any update/delete/add event. So to be 100% consistent, we then have to subscribe again, call the request endpoint and then start processing the subscription events. So in my view, the [route-level idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-idle-timeout) for the subscription endpoint should be set by default to 0. And yes, one can argue because of security measurements:

>  In other words, this timeout defends against a peer that does not release enough window to completely write the stream, even though all data has been proxied within available flow control windows.

but I guess, as far as JAGW is only internally available (does anyone share his network infrastructure to the public?) the risk of internal DoS is marginal.

This is just my view of the situation. I will respect your decision. :)

Greetings Pascal

**Comment by ILLIDOM** [comment]
Hello Pascal,

You are right, if the network is stable, the timeout will always be reached (regardless of the size of the timeout). But as you and I mentioned, the timeout behavior can be easily configured in the Envoy configuration according to the use case and preference.

I'm fine with your suggestion to set the default timeout to 0 inside the CM, as this is easier and more convenient for end application developers. Feel free to create a pull request with your changes, otherwise I will change the CM soon.

I'm not entirely sure that security can be neglected just because an application is deployed internally, but I agree that the benefit of disabling the timeout outweighs the security concerns in this case :D

Thanks for your input.

**Comment by ILLIDOM** [comment]
The default value has been changed, see [Pull Request](https://github.com/jalapeno-api-gateway/jagw/pull/55).
